services:

    PrestaShop\Module\DemoConsoleCommand\Command\ListManufacturerNamesCommand:
        class: PrestaShop\Module\DemoConsoleCommand\Command\ListManufacturerNamesCommand
        arguments:
            - '@prestashop.core.query_bus'
        tags: [ console.command ]
